{% set name = "mkdocs-get-deps" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_get_deps-{{ version }}.tar.gz
  sha256: 162b3d129c7fad9b19abfdcb9c1458a651628e4b1dea628ac68790fb3061c60c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - mkdocs-get-deps = mkdocs_get_deps.__main__:cli


requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - importlib-metadata >=4.3
    - mergedeep >=1.3.4
    - platformdirs >=2.2.0
    - pyyaml >=5.1

test:
  imports:
    - mkdocs_get_deps
  commands:
    - pip check
    - mkdocs-get-deps --help
  requires:
    - pip

about:
  summary: MkDocs extension that lists all dependencies according to a mkdocs.yml file
  home: https://github.com/mkdocs/get-deps
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - dhirschfeld
